import { BPDataType } from "./contexts/BPDataContext";
import uuid from "react-native-uuid";

export const mockBPData: BPDataType[] = [
  {
    id: uuid.v4() as string,
    day: "Mon",
    date: "Jun 5",
    time: "08:30 AM",
    bp_sys: 103,
    bp_dia: 75,
    pr: 71,
  },
  {
    id: uuid.v4() as string,
    day: "Tue",
    date: "Jun 6",
    time: "09:00 AM",
    bp_sys: 120,
    bp_dia: 80,
    pr: 78,
  },
  {
    id: uuid.v4() as string,
    day: "Wed",
    date: "Jun 7",
    time: "10:15 AM",
    bp_sys: 145,
    bp_dia: 95,
    pr: 82,
  },
  {
    id: uuid.v4() as string,
    day: "Thu",
    date: "Jun 8",
    time: "08:00 AM",
    bp_sys: 110,
    bp_dia: 70,
    pr: 65,
  },
  {
    id: uuid.v4() as string,
    day: "Fri",
    date: "Jun 9",
    time: "07:30 AM",
    bp_sys: 98,
    bp_dia: 60,
    pr: 72,
  },
  {
    id: uuid.v4() as string,
    day: "Sat",
    date: "Jun 10",
    time: "06:45 AM",
    bp_sys: 180,
    bp_dia: 110,
    pr: 90,
  },
  {
    id: uuid.v4() as string,
    day: "Sun",
    date: "Jun 11",
    time: "11:00 AM",
    bp_sys: 130,
    bp_dia: 85,
    pr: 76,
  },
  {
    id: uuid.v4() as string,
    day: "Mon",
    date: "Jun 12",
    time: "08:30 AM",
    bp_sys: 102,
    bp_dia: 65,
    pr: 60,
  },
  {
    id: uuid.v4() as string,
    day: "Tue",
    date: "Jun 13",
    time: "09:00 AM",
    bp_sys: 160,
    bp_dia: 100,
    pr: 85,
  },
  {
    id: uuid.v4() as string,
    day: "Wed",
    date: "Jun 14",
    time: "10:15 AM",
    bp_sys: 105,
    bp_dia: 66,
    pr: 74,
  },
  {
    id: uuid.v4() as string,
    day: "Thu",
    date: "Jun 15",
    time: "08:00 AM",
    bp_sys: 99,
    bp_dia: 58,
    pr: 63,
  },
  {
    id: uuid.v4() as string,
    day: "Fri",
    date: "Jun 16",
    time: "07:30 AM",
    bp_sys: 142,
    bp_dia: 93,
    pr: 88,
  },
  {
    id: uuid.v4() as string,
    day: "Sat",
    date: "Jun 17",
    time: "06:45 AM",
    bp_sys: 175,
    bp_dia: 105,
    pr: 95,
  },
  {
    id: uuid.v4() as string,
    day: "Sun",
    date: "Jun 18",
    time: "11:00 AM",
    bp_sys: 115,
    bp_dia: 77,
    pr: 70,
  },
  {
    id: uuid.v4() as string,
    day: "Mon",
    date: "Jun 19",
    time: "08:30 AM",
    bp_sys: 100,
    bp_dia: 63,
    pr: 68,
  },
  {
    id: uuid.v4() as string,
    day: "Tue",
    date: "Jun 20",
    time: "09:00 AM",
    bp_sys: 168,
    bp_dia: 104,
    pr: 86,
  },
  {
    id: uuid.v4() as string,
    day: "Wed",
    date: "Jun 21",
    time: "10:15 AM",
    bp_sys: 122,
    bp_dia: 81,
    pr: 73,
  },
];
